name: tripeaks_neue
description: "A TriPeaks patience (solitaire)"

version: 0.8.0

environment:
  sdk: ^3.7.0

dependencies:
  audioplayers: ^6.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.3.0
  intl: any
  logger: ^2.5.0
  mobx: ^2.5.0
  path_provider: ^2.1.5
  provider: ^6.1.2

  # cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  mobx_codegen: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - images/tropy.png
    - images/empty.png
    - images/welcome.png
    - sounds/take1.mp3
    - sounds/take2.mp3
    - sounds/take3.mp3
    - sounds/draw.mp3
    - sounds/undo.mp3
    - sounds/error.mp3
    - sounds/start.mp3
    - sounds/win.mp3
    - sounds/gameover.mp3

  fonts:
    - family: Actions
      fonts:
        - asset: fonts/actions.ttf
    - family: Cards
      fonts:
        - asset: fonts/cards.ttf
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-VariableFont_wght.ttf